# Generated by Django 5.2.3 on 2025-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=90)),
                ('prod_cat', models.CharField(max_length=90)),
                ('prod_vendor', models.CharField(max_length=90)),
                ('prod_mfg_date', models.DateTimeField()),
            ],
        ),
    ]
