# Generated by Django 5.2.3 on 2025-06-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=90)),
                ('cust_cat', models.CharField(max_length=90)),
                ('cust_vendor', models.CharField(max_length=90)),
                ('cust_mfg_date', models.DateTimeField()),
            ],
        ),
    ]
