# Generated by Django 5.2.3 on 2025-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=90)),
                ('cust_email', models.CharField(max_length=90)),
                ('cust_address', models.CharField(max_length=90)),
                ('cust_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
