# Generated by Django 5.2.3 on 2025-07-22 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_actor_author_order_user_book_movie_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_cat',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_mfg_date',
            new_name='product_manufacturing_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_vendor',
            new_name='product_vendor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='Product.actor'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.customers'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='product_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Product.author'),
        ),
    ]
